<?php
    $e = $this->element;
    $label = trim($e->getLabel());
    $id_element = ($e->getAttribute('type') == 'radio' && isset($value) ? $e->getAttribute('id').'-'.$value : $e->getAttribute('id'));
    $colsLabel = $this->colsLabel;
?>
<label class="control-label col-xs-<?=$colsLabel?> <?=($e->getAttribute('required') ? ' required' : '')?>" for="<?= $id_element ?>">
    <?php if($label) { ?><?= $this->translate($label) ?><?php } else{ echo '&nbsp;'; }?>
</label>
