<?php
    $e = $this->element;
    $label = trim($e->getLabel());
    $id_element = ($e->getAttribute('type') == 'radio' && isset($value) ? $e->getAttribute('id').'-'.$value : $e->getAttribute('id'));
    $colsLabel = $this->colsLabel;
?>
<div class="col-xs-<?=$colsLabel?>">
    <label class="control-label <?=($e->getAttribute('required') ? ' required' : '')?>" for="<?= $id_element ?>">
        <?php if($label) { ?><?= $this->translate($label) ?><?php } else{ echo '&nbsp;'; }?>
    </label>
</div>
