<?php
    $e = $this->element;
    $labelHelper = $this->formLabel();
    $label = $e->getLabel();
    $labelHelperTranlator = $labelHelper->getTranslator();
    if($label AND $labelHelperTranlator) {
        $label = $labelHelperTranlator->translate($label, $labelHelper->getTranslatorTextDomain());
    }
    $extended = $e->getOption('extended');
    $required = ($e->getAttribute('required') == 'required') ? 'required="required"' : false;
    $err = (count($e->getMessages()) > 0) ? $e->getMessages() : false;
?>

<div class="row-fluid">
    <div class="panel panel-default toggle sheep_it_replicator">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-target="#<?=$e->getName()?>" href="javascript:;" id="toggle_link">
                    <?=$e->getLabel()?>
                </a>

                <?php if(count($e->getForms()) > 1): ?>
                <select id="<?=$e->getName()?>_selector"> 
                    <option></option>
                    <?php foreach($e->getForms() as $key => $value):?>
                        <option value="<?=$key?>"><?=$key?></option>
                    <?php endforeach; ?>
                </select>
                <?php endif; ?>
                
                <span id="<?=$e->getName()?>_controls">
                    <a id="<?=$e->getName()?>_add" href="#" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-plus"></span> Add <?=$e->singularLabel()?></a>
                    <a id="<?=$e->getName()?>_remove_all" href="#" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-minus"></span> Remove All</a>
                </span>
            </h4>
        </div>
        <div id="<?=$e->getName()?>" class="panel-collapse collapse in">
            <div class="panel-body p0">
                <input type="hidden" name="<?=$e->getName()?>_active" value="<?=($e->getDisabled() ? 0 : 1)?>"/>
                <?php echo $e->render($this); ?>
                <div style="margin:8px;" id="<?=$e->getName()?>_noforms_template">No registers found</div>
            </div>
        </div>
    </div>
</div>
<?php if($e->initData()):?>
    <script><?= $e->initData() ?> </script>
<?php endif; ?>

<?php if($e->getDisabled()):?>
    <script>
    $(document).ready(function(){ 
        $(window).load( function() {
        window.<?= $e->getName() ?>_sheepit_obj.disable();
    })});
    </script>
<?php endif; ?>
