<?php
    $e = $this->element;
    $labelHelper = $this->formLabel();
    $label = $e->getLabel();
    $labelHelperTranlator = $labelHelper->getTranslator();
    if($label AND $labelHelperTranlator) {
        $label = $labelHelperTranlator->translate($label, $labelHelper->getTranslatorTextDomain());
    }
    $extended = $e->getOption('extended');
    $required = ($e->getAttribute('required') == 'required') ? 'required="required"' : false;
    $err = (count($e->getMessages()) > 0) ? $e->getMessages() : false;
    
    if($e->getAttribute('disabled') === "true"){
     //   $e->setDisabled(true);
    }
?>



<div class="row-fluid">
    <div class="panel panel-default sheep_it_replicator <?= $e->getAttribute('class') ?>">
        <div class="panel-heading active">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-target="#<?=$e->getName()?>" href="javascript:;" class="sheep_it_replicator_title">
                    <?= $label ?>
                    <?php if(count($e->getForms()) > 1): ?>
                    <select id="search_selector" class="form_field_st1" style="min-width: 100px; margin-left: 5px;">
                        <?php foreach($e->getForms() as $key => $value):?>
                            <option value="<?=$key?>"><?=$key?></option>
                        <?php endforeach; ?>
                    </select>
                    <?php endif; ?>

                    <span id="<?=$e->getName()?>_controls">
                        <select id="<?=$e->getName()?>_selector" style="display: none;"> </select>
                        <button type="button" id="<?=$e->getName()?>_add" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-plus"></span> Add <?=$e->singularLabel()?></button>
                        <button type="button" id="<?=$e->getName()?>_remove_all" class="btn btn-xs btn-primary"><span class="glyphicon glyphicon-minus"></span> Remove All</button>
                    </span>
                    <span style="float:right">
                        <?php if($e->closeButton()): ?> <span id="close" class="redcolor my_icon glyphicon glyphicon-remove" onclick="<?=$e->getName() ?>_sheepit_obj.close();"></span>    <?php endif; ?>
                    </span>
                </a>
            </h4>
        </div>
        <div id="<?=$e->getName()?>" class="panel-collapse collapse in">
            <div class="panel-body">
                <input type="hidden" name="<?=$e->getName()?>_active" value="<?=($e->getDisabled() ? 0 : 1)?>"/>
                <?php echo $e->render($this); ?>
                <div style="margin:8px;" id="<?=$e->getName()?>_noforms_template">No registers found</div>
            </div>
        </div>
    </div>
</div>

<?php 
$renderer->addJsCodeAfter($e->initData());

if($e->getDisabled()){
    $renderer->addJsCodeAfter('window.'.$e->getName().'_sheepit_obj.disable();');
}
