<?php
    $e = $this->element;
    $e->setAttribute('class', $e->getAttribute('class').' form-control');
    $label = $this->translate($e->getLabel());
    $extended = $e->getOption('extended');
    $err = (count($e->getMessages()) > 0) ? $e->getMessages() : false;
    $showInPanel = $e->getOption('showInPanel');
    $note = $e->getOption('note');
    $id = $e->getAttribute('id');
?>
<?php if($showInPanel): ?>
<div class="panel panel-default gutters-7 form-group">
    <div class="panel-heading active">
        <h4 class="panel-title">
            <a data-toggle="collapse" data-target="#<?=$id?>_panel" href="javascript:;"><?=$label?></a>
        </h4>
    </div>
    <div id="<?=$id?>_panel" class="panel-collapse collapse in">
        <div class="panel-body pr2 p0">                
            <?php if($note):?>
            <div class="tinyMceNote"><?=$note?></div>
            <?php endif; ?>
<?php endif; ?>
<div class="elementWrapper">
    <?php echo $this->formTextarea($e);
    if(isset($extended['help'])):?>
    <span class="help-block mobile_only">
        <?=$this->translate($extended['help']['content']) ?>
    </span>
    <?php endif;
          if($err) { ?>
<span class="help-block with-errors" style="display:none;">
    <ul>
    <?php foreach($err as $k => $v) { ?>
    	<li><?=$this->translate($v)?></li>
    <?php } ?>
    </ul>
</span>
    <?php } ?>
</div>
<?php if($showInPanel): ?>
        </div>
    </div>
</div>
<?php endif; ?>

